# Generated by Django 5.2.4 on 2025-08-18 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventreaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventreaction',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_48754f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreaction',
            index=models.Index(fields=['user'], name='events_even_user_id_07b7c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreaction',
            unique_together={('user', 'event')},
        ),
    ]
